/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author HEWLETT-PACKARD
 */
public class hangmanGUI extends javax.swing.JFrame {

    Random rand = new Random();
    String displayoutput="",guess="";
    String words[]= {"HELLO","WOMAN","BEAST","HARRY"};
    String hints[] = {"HI","MAN","BEAUTY","POTTER"};
    int dup[]= new int[words.length];

    int counter=0,r,score=0,win=0,life=5,scorecheck;
    char letter;
    /**
     * Creates new form hangmanGUI
     */
    
    public hangmanGUI() {
        setTitle("Hangman Natsu Version");
        initComponents();
        set();
        System.out.print(guess);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bA = new javax.swing.JButton();
        bB = new javax.swing.JButton();
        bC = new javax.swing.JButton();
        bD = new javax.swing.JButton();
        bE = new javax.swing.JButton();
        bF = new javax.swing.JButton();
        bG = new javax.swing.JButton();
        bH = new javax.swing.JButton();
        bI = new javax.swing.JButton();
        bJ = new javax.swing.JButton();
        bK = new javax.swing.JButton();
        bL = new javax.swing.JButton();
        bM = new javax.swing.JButton();
        bN = new javax.swing.JButton();
        bO = new javax.swing.JButton();
        bP = new javax.swing.JButton();
        bQ = new javax.swing.JButton();
        bR = new javax.swing.JButton();
        bS = new javax.swing.JButton();
        bT = new javax.swing.JButton();
        bU = new javax.swing.JButton();
        bV = new javax.swing.JButton();
        bW = new javax.swing.JButton();
        bX = new javax.swing.JButton();
        bY = new javax.swing.JButton();
        bZ = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bNewGame = new javax.swing.JButton();
        bReveal = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        dispAns = new javax.swing.JLabel();
        Hints = new javax.swing.JLabel();
        natsu = new javax.swing.JLabel();
        natsu2 = new javax.swing.JLabel();
        natsu3 = new javax.swing.JLabel();
        chair = new javax.swing.JLabel();
        stand = new javax.swing.JLabel();
        base = new javax.swing.JLabel();
        branch = new javax.swing.JLabel();
        rope = new javax.swing.JLabel();
        lbl_life = new javax.swing.JLabel();
        lbl_Count = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(getBackground());
        setForeground(new java.awt.Color(0, 0, 153));
        setPreferredSize(new java.awt.Dimension(1050, 595));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        bA.setBackground(new java.awt.Color(153, 204, 255));
        bA.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bA.setForeground(new java.awt.Color(255, 102, 0));
        bA.setText("A");
        bA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAActionPerformed(evt);
            }
        });

        bB.setBackground(new java.awt.Color(153, 204, 255));
        bB.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bB.setForeground(new java.awt.Color(255, 102, 0));
        bB.setText("B");
        bB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBActionPerformed(evt);
            }
        });

        bC.setBackground(new java.awt.Color(153, 204, 255));
        bC.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bC.setForeground(new java.awt.Color(255, 102, 0));
        bC.setText("C");
        bC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCActionPerformed(evt);
            }
        });

        bD.setBackground(new java.awt.Color(153, 204, 255));
        bD.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bD.setForeground(new java.awt.Color(255, 102, 0));
        bD.setText("D");
        bD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDActionPerformed(evt);
            }
        });

        bE.setBackground(new java.awt.Color(153, 204, 255));
        bE.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bE.setForeground(new java.awt.Color(255, 102, 0));
        bE.setText("E");
        bE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEActionPerformed(evt);
            }
        });

        bF.setBackground(new java.awt.Color(153, 204, 255));
        bF.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bF.setForeground(new java.awt.Color(255, 102, 0));
        bF.setText("F");
        bF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFActionPerformed(evt);
            }
        });

        bG.setBackground(new java.awt.Color(153, 204, 255));
        bG.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bG.setForeground(new java.awt.Color(255, 102, 0));
        bG.setText("G");
        bG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGActionPerformed(evt);
            }
        });

        bH.setBackground(new java.awt.Color(153, 204, 255));
        bH.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bH.setForeground(new java.awt.Color(255, 102, 0));
        bH.setText("H");
        bH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHActionPerformed(evt);
            }
        });

        bI.setBackground(new java.awt.Color(153, 204, 255));
        bI.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bI.setForeground(new java.awt.Color(255, 102, 0));
        bI.setText("I");
        bI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIActionPerformed(evt);
            }
        });

        bJ.setBackground(new java.awt.Color(153, 204, 255));
        bJ.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bJ.setForeground(new java.awt.Color(255, 102, 0));
        bJ.setText("J");
        bJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJActionPerformed(evt);
            }
        });

        bK.setBackground(new java.awt.Color(153, 204, 255));
        bK.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bK.setForeground(new java.awt.Color(255, 102, 0));
        bK.setText("K");
        bK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKActionPerformed(evt);
            }
        });

        bL.setBackground(new java.awt.Color(153, 204, 255));
        bL.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bL.setForeground(new java.awt.Color(255, 102, 0));
        bL.setText("L");
        bL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLActionPerformed(evt);
            }
        });

        bM.setBackground(new java.awt.Color(153, 204, 255));
        bM.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bM.setForeground(new java.awt.Color(255, 102, 0));
        bM.setText("M");
        bM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMActionPerformed(evt);
            }
        });

        bN.setBackground(new java.awt.Color(153, 204, 255));
        bN.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bN.setForeground(new java.awt.Color(255, 102, 0));
        bN.setText("N");
        bN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNActionPerformed(evt);
            }
        });

        bO.setBackground(new java.awt.Color(153, 204, 255));
        bO.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bO.setForeground(new java.awt.Color(255, 102, 0));
        bO.setText("O");
        bO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOActionPerformed(evt);
            }
        });

        bP.setBackground(new java.awt.Color(153, 204, 255));
        bP.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bP.setForeground(new java.awt.Color(255, 102, 0));
        bP.setText("P");
        bP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPActionPerformed(evt);
            }
        });

        bQ.setBackground(new java.awt.Color(153, 204, 255));
        bQ.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bQ.setForeground(new java.awt.Color(255, 102, 0));
        bQ.setText("Q");
        bQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQActionPerformed(evt);
            }
        });

        bR.setBackground(new java.awt.Color(153, 204, 255));
        bR.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bR.setForeground(new java.awt.Color(255, 102, 0));
        bR.setText("R");
        bR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRActionPerformed(evt);
            }
        });

        bS.setBackground(new java.awt.Color(153, 204, 255));
        bS.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bS.setForeground(new java.awt.Color(255, 102, 0));
        bS.setText("S");
        bS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSActionPerformed(evt);
            }
        });

        bT.setBackground(new java.awt.Color(153, 204, 255));
        bT.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bT.setForeground(new java.awt.Color(255, 102, 0));
        bT.setText("T");
        bT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTActionPerformed(evt);
            }
        });

        bU.setBackground(new java.awt.Color(153, 204, 255));
        bU.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bU.setForeground(new java.awt.Color(255, 102, 0));
        bU.setText("U");
        bU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUActionPerformed(evt);
            }
        });

        bV.setBackground(new java.awt.Color(153, 204, 255));
        bV.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bV.setForeground(new java.awt.Color(255, 102, 0));
        bV.setText("V");
        bV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVActionPerformed(evt);
            }
        });

        bW.setBackground(new java.awt.Color(153, 204, 255));
        bW.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bW.setForeground(new java.awt.Color(255, 102, 0));
        bW.setText("W");
        bW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bWActionPerformed(evt);
            }
        });

        bX.setBackground(new java.awt.Color(153, 204, 255));
        bX.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bX.setForeground(new java.awt.Color(255, 102, 0));
        bX.setText("X");
        bX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bXActionPerformed(evt);
            }
        });

        bY.setBackground(new java.awt.Color(153, 204, 255));
        bY.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bY.setForeground(new java.awt.Color(255, 102, 0));
        bY.setText("Y");
        bY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bYActionPerformed(evt);
            }
        });

        bZ.setBackground(new java.awt.Color(153, 204, 255));
        bZ.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bZ.setForeground(new java.awt.Color(255, 102, 0));
        bZ.setText("Z");
        bZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bL)
                                .addGap(5, 5, 5)
                                .addComponent(bM)
                                .addGap(5, 5, 5)
                                .addComponent(bN)
                                .addGap(5, 5, 5)
                                .addComponent(bO)
                                .addGap(5, 5, 5)
                                .addComponent(bP)
                                .addGap(5, 5, 5)
                                .addComponent(bQ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bR))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bX, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bY, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bS, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bV))
                            .addComponent(bZ, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(bA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bB)
                        .addGap(5, 5, 5)
                        .addComponent(bC)
                        .addGap(5, 5, 5)
                        .addComponent(bD)
                        .addGap(5, 5, 5)
                        .addComponent(bE)
                        .addGap(5, 5, 5)
                        .addComponent(bF)
                        .addGap(5, 5, 5)
                        .addComponent(bG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bI)
                        .addGap(2, 2, 2)
                        .addComponent(bJ, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bK)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bA)
                        .addComponent(bB)
                        .addComponent(bC)
                        .addComponent(bD)
                        .addComponent(bE)
                        .addComponent(bF)
                        .addComponent(bG)
                        .addComponent(bH))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bI)
                        .addComponent(bK)
                        .addComponent(bJ)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bQ)
                                .addComponent(bR)
                                .addComponent(bU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bV)
                                .addComponent(bT))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bY)
                    .addComponent(bZ)
                    .addComponent(bX)
                    .addComponent(bW))
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 350, 680, 207);

        jPanel3.setOpaque(false);

        bNewGame.setBackground(new java.awt.Color(153, 204, 255));
        bNewGame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bNewGame.setText("NEW GAME");
        bNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewGameActionPerformed(evt);
            }
        });

        bReveal.setBackground(new java.awt.Color(153, 204, 255));
        bReveal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bReveal.setText("REVEAL WORD");
        bReveal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRevealActionPerformed(evt);
            }
        });

        bExit.setBackground(new java.awt.Color(153, 204, 255));
        bExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bExit.setText("EXIT");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bReveal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bNewGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bReveal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bExit)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(810, 420, 200, 113);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);

        title.setBackground(new java.awt.Color(255, 204, 51));
        title.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 102, 0));
        title.setText("HANGMAN GAME");

        dispAns.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        dispAns.setText("_ _ _ _ _");

        Hints.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Hints.setForeground(new java.awt.Color(255, 102, 0));
        Hints.setText(hints[r]);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(title))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Hints, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dispAns)
                .addGap(222, 222, 222))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Hints, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(dispAns)
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 10, 646, 326);

        natsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natsu1.png"))); // NOI18N
        natsu.setText("jLabel2");
        getContentPane().add(natsu);
        natsu.setBounds(900, 140, 110, 150);

        natsu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NATSU2.png"))); // NOI18N
        natsu2.setText("jLabel1");
        getContentPane().add(natsu2);
        natsu2.setBounds(900, 140, 120, 152);

        natsu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/natsu3.png"))); // NOI18N
        natsu3.setText("jLabel1");
        getContentPane().add(natsu3);
        natsu3.setBounds(910, 130, 110, 160);

        chair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chair.png"))); // NOI18N
        chair.setText("jLabel3");
        getContentPane().add(chair);
        chair.setBounds(920, 270, 80, 80);

        stand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stand.png"))); // NOI18N
        stand.setText("jLabel7");
        getContentPane().add(stand);
        stand.setBounds(780, 37, 50, 300);

        base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/base.png"))); // NOI18N
        base.setText("jLabel9");
        getContentPane().add(base);
        base.setBounds(740, 320, 310, 70);

        branch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/branch.png"))); // NOI18N
        branch.setText("jLabel10");
        getContentPane().add(branch);
        branch.setBounds(820, 60, 197, 40);

        rope.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rope.png"))); // NOI18N
        rope.setText("jLabel1");
        getContentPane().add(rope);
        rope.setBounds(930, 80, 40, 130);

        lbl_life.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_life.setText("LIFE:");
        getContentPane().add(lbl_life);
        lbl_life.setBounds(680, 20, 50, 40);

        lbl_Count.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Count.setText("5");
        getContentPane().add(lbl_Count);
        lbl_Count.setBounds(730, 20, 20, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAActionPerformed
        bA.setEnabled(false);
                letter='A';
                  check();
    }//GEN-LAST:event_bAActionPerformed

    private void bBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBActionPerformed
        bB.setEnabled(false);
                letter='B';
                check();
    }//GEN-LAST:event_bBActionPerformed

    private void bCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCActionPerformed
        bC.setEnabled(false);   
             letter='C';   
             check();   
    }//GEN-LAST:event_bCActionPerformed

    private void bDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDActionPerformed
        bD.setEnabled(false);
                letter='D';
                check();
    }//GEN-LAST:event_bDActionPerformed

    private void bPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPActionPerformed
        bP.setEnabled(false);
                letter='P';
                check();
    }//GEN-LAST:event_bPActionPerformed

    private void bWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWActionPerformed
        bW.setEnabled(false);
                letter='W';
                check();
    }//GEN-LAST:event_bWActionPerformed

    private void bNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewGameActionPerformed
            bA.setEnabled(true);
            bB.setEnabled(true);
            bC.setEnabled(true);
            bD.setEnabled(true);
            bE.setEnabled(true);
            bF.setEnabled(true);
            bG.setEnabled(true);
            bH.setEnabled(true);
            bI.setEnabled(true);
            bJ.setEnabled(true);
            bK.setEnabled(true);
            bL.setEnabled(true);
            bM.setEnabled(true);
            bN.setEnabled(true);
            bO.setEnabled(true);
            bP.setEnabled(true);
            bQ.setEnabled(true);
            bR.setEnabled(true);
            bS.setEnabled(true);
            bT.setEnabled(true);
            bU.setEnabled(true);
            bV.setEnabled(true);
            bW.setEnabled(true);
            bX.setEnabled(true);
            bY.setEnabled(true);
            bZ.setEnabled(true);
            set();
            natsu.setVisible(true);
            natsu2.setVisible(false);
            chair.setVisible(true);
            base.setVisible(false);
            stand.setVisible(false);
            branch.setVisible(false);
            rope.setVisible(false);
            natsu2.setVisible(false);
            natsu3.setVisible(false);
     
    }//GEN-LAST:event_bNewGameActionPerformed

    private void bEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEActionPerformed
        bE.setEnabled(false);
                letter='E';
                check();
    }//GEN-LAST:event_bEActionPerformed

    private void bFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFActionPerformed
        bF.setEnabled(false);
                letter='F';
               check();
    }//GEN-LAST:event_bFActionPerformed

    private void bGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGActionPerformed
        bG.setEnabled(false);
                letter='G';
                check();
    }//GEN-LAST:event_bGActionPerformed

    private void bHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHActionPerformed
        bH.setEnabled(false);
                letter='H';
                check();
    }//GEN-LAST:event_bHActionPerformed

    private void bIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIActionPerformed
        bI.setEnabled(false);
                letter='I';
                check();
    }//GEN-LAST:event_bIActionPerformed

    private void bJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJActionPerformed
        bJ.setEnabled(false);
                letter='J';
                check();
    }//GEN-LAST:event_bJActionPerformed

    private void bKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKActionPerformed
        bK.setEnabled(false);
                letter='K';
                check();
    }//GEN-LAST:event_bKActionPerformed

    private void bLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLActionPerformed
        bL.setEnabled(false);
                letter='L';
                check();
    }//GEN-LAST:event_bLActionPerformed

    private void bMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMActionPerformed
        bM.setEnabled(false);
                letter='M';
                check();
    }//GEN-LAST:event_bMActionPerformed

    private void bNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNActionPerformed
        bN.setEnabled(false);     
                letter='N';
                check();      
    }//GEN-LAST:event_bNActionPerformed

    private void bOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOActionPerformed
        bO.setEnabled(false);
                letter='O';
                check();
    }//GEN-LAST:event_bOActionPerformed

    private void bQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQActionPerformed
      bQ.setEnabled(false);
                letter='Q';
                check();
    }//GEN-LAST:event_bQActionPerformed

    private void bRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRActionPerformed
        bR.setEnabled(false);
                letter='R';
                check();
    }//GEN-LAST:event_bRActionPerformed

    private void bTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTActionPerformed
        bT.setEnabled(false);
                letter='T';
                check();
    }//GEN-LAST:event_bTActionPerformed

    private void bUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUActionPerformed
       bU.setEnabled(false);
               letter='U';
               check();
       
    }//GEN-LAST:event_bUActionPerformed

    private void bVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVActionPerformed
        bV.setEnabled(false);
                letter='V';
                check();
        
    }//GEN-LAST:event_bVActionPerformed

    private void bXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bXActionPerformed
        bX.setEnabled(false);
                letter='X';
                check();
        
    }//GEN-LAST:event_bXActionPerformed

    private void bYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bYActionPerformed
        bY.setEnabled(false);
                letter='Y';
               check();
    }//GEN-LAST:event_bYActionPerformed

    private void bZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZActionPerformed
        bZ.setEnabled(false);
                letter='Z';
                check();
    }//GEN-LAST:event_bZActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        base.setVisible(false);
        stand.setVisible(false);
        branch.setVisible(false);
        rope.setVisible(false);
        
        
        natsu2.setVisible(false);
        natsu3.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void bRevealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRevealActionPerformed
        // TODO add your handling code here:
                            dispAns.setText(guess);
                            bA.setEnabled(false);
                            bB.setEnabled(false);
                            bC.setEnabled(false);
                            bD.setEnabled(false);
                            bE.setEnabled(false);
                            bF.setEnabled(false);
                            bG.setEnabled(false);
                            bH.setEnabled(false);
                            bI.setEnabled(false);
                            bJ.setEnabled(false);
                            bK.setEnabled(false);
                            bL.setEnabled(false);
                            bM.setEnabled(false);
                            bN.setEnabled(false);
                            bO.setEnabled(false);
                            bP.setEnabled(false);
                            bQ.setEnabled(false);
                            bR.setEnabled(false);
                            bS.setEnabled(false);
                            bT.setEnabled(false);
                            bU.setEnabled(false);
                            bV.setEnabled(false);
                            bW.setEnabled(false);
                            bX.setEnabled(false);
                            bY.setEnabled(false);
                            bZ.setEnabled(false);
    }//GEN-LAST:event_bRevealActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void bSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSActionPerformed
        bS.setEnabled(false);
                letter='S';
                check();
    }//GEN-LAST:event_bSActionPerformed

       public void set(){
            life=5;
            displayoutput="";
            score=0;
            this.r = rand.nextInt(words.length);
            for(int i=0;i<words.length;i++){
                if(dup[i]== r){
                    this.r = rand.nextInt(words.length);
                }
            }
            guess= words[r];
            for(int i=0;i<guess.length();i++){
                displayoutput=displayoutput +"-";
            }
            dispAns.setText(displayoutput);
            lbl_Count.setText(String.valueOf(life));
            
            
            
        }
      public void check(){
        int j=0;
        scorecheck=score;
        for(int i=0;i<guess.length();i++){
            char conv=guess.charAt(i);
            if(conv == letter){
                char[] dispchar = displayoutput.toCharArray();
                dispchar[i]=conv;
                displayoutput = String.valueOf(dispchar);
                score++;
            }
        }
        
        dispAns.setText(displayoutput);
        if(scorecheck==score){
            life--;
            lbl_Count.setText(String.valueOf(life));
            if(life==4){
                base.setVisible(true);
            }
            else if(life==3){
                stand.setVisible(true);
            }
            else if(life==2){
                branch.setVisible(true);
            }
            else if(life==1){
                rope.setVisible(true);
                natsu2.setVisible(true);
                natsu.setVisible(false);
            }
            else if(life==0){
                natsu3.setVisible(true);
                natsu.setVisible(false);
                natsu2.setVisible(false);
                chair.setVisible(false);
                JOptionPane.showMessageDialog(null,"Game Over!!!");
                            bA.setEnabled(false);
                            bB.setEnabled(false);
                            bC.setEnabled(false);
                            bD.setEnabled(false);
                            bE.setEnabled(false);
                            bF.setEnabled(false);
                            bG.setEnabled(false);
                            bH.setEnabled(false);
                            bI.setEnabled(false);
                            bJ.setEnabled(false);
                            bK.setEnabled(false);
                            bL.setEnabled(false);
                            bM.setEnabled(false);
                            bN.setEnabled(false);
                            bO.setEnabled(false);
                            bP.setEnabled(false);
                            bQ.setEnabled(false);
                            bR.setEnabled(false);
                            bS.setEnabled(false);
                            bT.setEnabled(false);
                            bU.setEnabled(false);
                            bV.setEnabled(false);
                            bW.setEnabled(false);
                            bX.setEnabled(false);
                            bY.setEnabled(false);
                            bZ.setEnabled(false);
            }
        }
        else if(score==guess.length()){
            JOptionPane.showMessageDialog(null,"You won!!!");
            natsu.setVisible(true);
            natsu2.setVisible(false);
            chair.setVisible(false);
            base.setVisible(false);
            stand.setVisible(false);
            branch.setVisible(false);
            rope.setVisible(false);
            natsu2.setVisible(false);
            natsu3.setVisible(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hangmanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new hangmanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hints;
    private javax.swing.JButton bA;
    private javax.swing.JButton bB;
    private javax.swing.JButton bC;
    private javax.swing.JButton bD;
    private javax.swing.JButton bE;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bF;
    private javax.swing.JButton bG;
    private javax.swing.JButton bH;
    private javax.swing.JButton bI;
    private javax.swing.JButton bJ;
    private javax.swing.JButton bK;
    private javax.swing.JButton bL;
    private javax.swing.JButton bM;
    private javax.swing.JButton bN;
    private javax.swing.JButton bNewGame;
    private javax.swing.JButton bO;
    private javax.swing.JButton bP;
    private javax.swing.JButton bQ;
    private javax.swing.JButton bR;
    private javax.swing.JButton bReveal;
    private javax.swing.JButton bS;
    private javax.swing.JButton bT;
    private javax.swing.JButton bU;
    private javax.swing.JButton bV;
    private javax.swing.JButton bW;
    private javax.swing.JButton bX;
    private javax.swing.JButton bY;
    private javax.swing.JButton bZ;
    private javax.swing.JLabel base;
    private javax.swing.JLabel branch;
    private javax.swing.JLabel chair;
    private javax.swing.JLabel dispAns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_Count;
    private javax.swing.JLabel lbl_life;
    private javax.swing.JLabel natsu;
    private javax.swing.JLabel natsu2;
    private javax.swing.JLabel natsu3;
    private javax.swing.JLabel rope;
    private javax.swing.JLabel stand;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
